### ISSUE TITLE
Auto heart rate and BP measurement time 30 minutes ahead

### ISSUE THREAD

**Issue by srijansaxena11** [ERap320/LenovoWatchMOD#12]
When I measure heart rate or BP manually then it is added to the record with correct time stamp and shown correct time on which it was measured. But when automatic measurement takes place (which is every 10 minutes I guess), it is added to the record with timestamp 30 minutes ahead of the time on which it was measured. Any solution for it? 
![Screenshot_2019-07-02-18-09-44-699_com pmpd dmap lenovo](https://user-images.githubusercontent.com/34964694/60513623-5ea06000-9cf5-11e9-9e32-bfbecec89c96.jpg)

**Comment by ERap320** [comment]
Sorry, I don't have a model with heart rate measuring, so I can't test anything about this.
