### ISSUE TITLE
Weather is not working in Italy

### ISSUE THREAD

**Issue by boscoad** [ERap320/LenovoWatchMOD#14]
In the app I see an alert with:
"length=2;
regionStart=3;
regionLength=1;
"
on the watch I see 69°C...

**Comment by Fito7** [comment]
The same problem. I live in Argentina
The app shows:
length=3;Index=4 
I think they will not solve the problem.

**Comment by Fito7** [comment]
Can it be resolved that the clock shows the weather outside of China?

**Comment by ERap320** [comment]
Is the problem still present with the latest release?

**Comment by Fito7** [comment]
> Is the problem still present with the latest release?

Yes. In addition to the latest version of the watch, they removed the weather on the watch and the App also in the recent version.  The only way to have the weather is by going down to version 0.7.3 of the watch and having gadgetbridge active on the phone.

**Comment by ERap320** [comment]
Since the app doesn't offer the feature anymore I'll close the issue
