### ISSUE TITLE
App is not working because of "Server busy"

### ISSUE THREAD

**Issue by zGitHubDev** [ERap320/LenovoWatchMOD#15]
Hi,

I faced with this issue before more times, but sooner or later it was fixed, but the problem is come up again more often, and it will be good, if have at least a workaround for it.
Problem: 
Watch App can't connect to Lenovo server . The error message: "The server is busy, please try it again later".

Side effect:

- If you are logged in, you can use the app, but data are not synchronized to the server, you can't check past data, like HR or Sleep data.
-  If you are not logged in (e.g. you have a new phone and installed the app right now), you can't do anything the app stay in the login page, and if you try to use the Dont Login button you will get the same error.:(

Any idea?

Regards

**Comment by ERap320** [comment]
Does problem occur every time you try to use the application or is it transient?
The error message could be correctly displayed if Lenovo servers are experiencing some service interruption.

**Comment by Fito7** [comment]
I have the same problem with my lenovo watch x plus. It says "server busy". I sent an email reporting that, but nobody responded to me.

**Comment by zGitHubDev** [comment]
Hi, the error is always presented in the last few days when I tried, and yes it can be a server issues as a lot of complain arrived to lenovo forum also, can somehow ignore the connection to the server?

**Comment by ERap320** [comment]
I doubt it. Some time ago, before making the _noupdate_ version, I also tried to completely cut off internet connection to the up, but it made everything unusable.

**Comment by Fito7** [comment]
The app says server busy for at least two months ago, ever day. It only shows the steps of the day.

**Comment by ERap320** [comment]
I guess they changed some API of their service and now only new versions of the app work correctly.
I'll try to check if newer versions of the official app are still protected with Quihoo.

This may be the end of this project.

**Comment by freeloader24** [comment]
> I guess they changed some API of their service and now only new versions of the app work correctly.
> I'll try to check if newer versions of the official app are still protected with Quihoo.
> 
> This may be the end of this project.

That should be the case. I have tried to install the official app which works fine (of course with the limitations) afterwards, deleted the app and installed the mod and constantly receiving the "no network" message. Even if I press "Don't log in". I assime, that the server side has been changed or the server rejects the connection from older versions of the app. is iPowerful the same? That also prevents modding?

**Comment by Fito7** [comment]
> > Supongo que cambiaron algunas API de su servicio y ahora solo las nuevas versiones de la aplicación funcionan correctamente. 
> > Intentaré verificar si las versiones más nuevas de la aplicación oficial todavía están protegidas con Quihoo.
> > Este puede ser el final de este proyecto.
> 
> Ese debería ser el caso. He tratado de instalar la aplicación oficial que funciona bien (por supuesto, con las limitaciones) después, eliminé la aplicación e instalé el mod y recibí constantemente el mensaje "sin red". Incluso si presiono "No iniciar sesión". Supongo que el lado del servidor ha cambiado o el servidor rechaza la conexión de versiones anteriores de la aplicación. ¿iPowerful es lo mismo? Eso también evita el modding?

Ipowerful also says server busy and rejects the request.  It's a shame what is happening and we have no information.  Also with the last update they deleted the weather line that can already be seen in unofficial versions like gadgetbridge, but those of us who have version 0.7.5 cannot see it on the clock because they deleted it.  It's a shame because the clock is beautiful and is doing very well.  But they don't support it with an Android application.

**Comment by freeloader24** [comment]
> > > Supongo que cambiaron algunas API de su servicio y ahora solo las nuevas versiones de la aplicación funcionan correctamente.
> > > Intentaré verificar si las versiones más nuevas de la aplicación oficial todavía están protegidas con Quihoo.
> > > Este puede ser el final de este proyecto.
> > 
> > 
> > Ese debería ser el caso. He tratado de instalar la aplicación oficial que funciona bien (por supuesto, con las limitaciones) después, eliminé la aplicación e instalé el mod y recibí constantemente el mensaje "sin red". Incluso si presiono "No iniciar sesión". Supongo que el lado del servidor ha cambiado o el servidor rechaza la conexión de versiones anteriores de la aplicación. ¿iPowerful es lo mismo? Eso también evita el modding?
> 
> Ipowerful also says server busy and rejects the request. It's a shame what is happening and we have no information. Also with the last update they deleted the weather line that can already be seen in unofficial versions like gadgetbridge, but those of us who have version 0.7.5 cannot see it on the clock because they deleted it. It's a shame because the clock is beautiful and works very well. But they don't support it with an Android application.

I can't connect with gatgetbridge. I have used the official version. Is there any way to use it?

**Comment by milisavt** [comment]
i can't log in anywhere, the clock has no function, (no network problem) i bought the clock two days ago, i didn't know there was a problem with using it, i installed apk from google play but in vain, any help

**Comment by ERap320** [comment]
> 
> 
> i can't log in anywhere, the clock has no function, (no network problem) i bought the clock two days ago, i didn't know there was a problem with using it, i installed apk from google play but in vain, any help

For now the best solution is to use Gadgetbridge

**Comment by Fito7** [comment]
Something very strange is happening with the server and ipowerful.  The other day I wanted to enter the ipowerful web domain and my browser found it insecure, for information theft, such as credit card information.  The Android application no longer allows registration.  All very strange.  Some time ago they had to update the watch for being insecure.

**Comment by milisavt** [comment]
> > i can't log in anywhere, the clock has no function, (no network problem) i bought the clock two days ago, i didn't know there was a problem with using it, i installed apk from google play but in vain, any help
> 
> For now the best solution is to use Gadgetbridge

on my xiaomi mi 9 with android 10 i failed to connect to any version of gadgetbrige. Lenovo watch x

**Comment by Fito7** [comment]
![Screenshot_20191220-112954](https://user-images.githubusercontent.com/53584987/71262397-54fbca80-231e-11ea-94b0-89816cf19a2f.png)
![Screenshot_20191220-113004](https://user-images.githubusercontent.com/53584987/71262399-55946100-231e-11ea-96f4-863f13660bc2.png)
![Screenshot_20191220-112850](https://user-images.githubusercontent.com/53584987/71262400-55946100-231e-11ea-9f87-b61e3dedb061.png)
Good news.  In the play store in China they have updated the application and it is working!

**Comment by milisavt** [comment]
> ![Screenshot_20191220-112954](https://user-images.githubusercontent.com/53584987/71262397-54fbca80-231e-11ea-94b0-89816cf19a2f.png)
> ![Screenshot_20191220-113004](https://user-images.githubusercontent.com/53584987/71262399-55946100-231e-11ea-96f4-863f13660bc2.png)
> ![Screenshot_20191220-112850](https://user-images.githubusercontent.com/53584987/71262400-55946100-231e-11ea-9f87-b61e3dedb061.png)
> Good news. In the play store in China they have updated the application and it is working!

Where to download

**Comment by Fito7** [comment]
https://3g.lenovomm.com/redsea/com.pmpd.dmap.lenovo

**Comment by milisavt** [comment]
> https://3g.lenovomm.com/redsea/com.pmpd.dmap.lenovo

Thanks so much for the help, I'm thrilled to be able to use it.  Thank you

**Comment by ERap320** [comment]
> 
> 
> https://3g.lenovomm.com/redsea/com.pmpd.dmap.lenovo

Good news! I tried to download and disassemble this chinese version and the code doesn't seem encrypted by Qihoo anymore.
I can't test it right now because my watch doesn't work, but I'm almost sure I will be able release a new version.

Anybody interested in testing the modified APK for me until I repair the watch?

**Comment by joelbars** [comment]
You can count with me.

**Comment by milisavt** [comment]
Me to🙂

**Comment by Fito7** [comment]
Me too.  Try to make the application spend less battery and eliminate advertising if it is possible.  I hope that the ipowerful application is updated too, since it has more information and gives more health tips.

**Comment by ERap320** [comment]
In the end I managed to fix the watch and test the new version myself. Thank you all anyway.
I still flagged this version as pre-release, waiting to hear if everything works for you too.

Feel free to try it: [3.1.0_noupdate](https://github.com/ERap320/LenovoWatchMOD/releases/tag/3.1.0_noupdate)

**Comment by Fito7** [comment]
Do not install the application.  Do I have to uninstall the official app ?.  Show this when installing:
![Screenshot_20191222-123429](https://user-images.githubusercontent.com/53584987/71323963-0c781480-24b8-11ea-9c91-c194c78c3d6b.png)

**Comment by ERap320** [comment]
Yes, you have to uninstall the other one

**Comment by Fito7** [comment]
The application works well as the official one.  Its mod allows to see future updates, but does not allow them to update ?.

**Comment by ERap320** [comment]
The mod prevents updates completely, since in the past the update dialogue made it impossible to use the app without updating. See #6.

**Comment by azagor** [comment]
It started to happen again. With the latest version of the app 3.14, it is unable to sync the data with server. Moreover the app was removed from google Play store. Anyone knows what is going on?

**Comment by ERap320** [comment]
> 
> 
> It started to happen again. With the latest version of the app 3.14, it is unable to sync the data with server. Moreover the app was removed from google Play store. Anyone knows what is going on?

They probably changed their APIs again, making old versions incompatible.
I see there is a 3.1.5 APK around, I'll see what I can do with that as soon as I can.

**Comment by azagor** [comment]
> > It started to happen again. With the latest version of the app 3.14, it is unable to sync the data with server. Moreover the app was removed from google Play store. Anyone knows what is going on?
> 
> They probably changed their APIs again, making old versions incompatible.
> I see there is a 3.1.5 APK around, I'll see what I can do with that as soon as I can.

Thank you! That would be great

**Comment by ERap320** [comment]
I just released [Version 3.1.5](https://github.com/ERap320/LenovoWatchMOD/releases/tag/3.1.5)
@azagor Please let me know if everything works with it

**Comment by azagor** [comment]
> I just released [Version 3.1.5](https://github.com/ERap320/LenovoWatchMOD/releases/tag/3.1.5)
> @azagor Please let me know if everything works with it

It seems to work. After login in to the lenovo account. I can't preview stored data ( maybe server is down) but other then that its all good. You are the best!

**Comment by azagor** [comment]
@ERap320  would you mind checking why syncing heart rate, sleep, mood et, is not working on all of the latest version of the app? You can log in to the Lenovo Account but that is it. No syncing data. There s always message "server busy please try again later". Mybe they have changed the adress and it was not updated in the app.  Another thing is the weather widget. Apprenlty it is not available ony beceasue it is has hardcodedcheck for location ( it must be China ). I will also gladly test stuff for you. Just let me know.

**Comment by ERap320** [comment]
> 
> 
> @ERap320 would you mind checking why syncing heart rate, sleep, mood etc, is not working on all of the latest version of the app? You can log in to the Lenovo Account but that is it. No syncing data. There is always message "server busy please try again later". Mybe they have changed the adress and it was not updated in the app. Another thing is the weather widget. Apprenlty it is not available ony beceasue it is has hardcoded check for location ( it must be China ). I will also gladly test stuff for you. Just let me know.

Have you checked if the official app v3.1.5 also has the same problems? You can find it on APKMirror.
Anyway, I think it would be difficult for me to reverse engineer and fix all those functions from decompiled code.

Could you also open a new issue for this problem? This way we can track it better.

**Comment by azagor** [comment]
> > @ERap320 would you mind checking why syncing heart rate, sleep, mood etc, is not working on all of the latest version of the app? You can log in to the Lenovo Account but that is it. No syncing data. There is always message "server busy please try again later". Mybe they have changed the adress and it was not updated in the app. Another thing is the weather widget. Apprenlty it is not available ony beceasue it is has hardcoded check for location ( it must be China ). I will also gladly test stuff for you. Just let me know.
> 
> Have you checked if the official app v3.1.5 also has the same problems? You can find it on APKMirror.
> Anyway, I think it would be difficult for me to reverse engineer and fix all those functions from decompiled code.
> 
> Could you also open a new issue for this problem? This way we can track it better.

Hey! Thank you for anwsering so fast! It does happen on the official app aswell. They broke it.  I checked all the official verisions staring from 3.1.0.  I understand the difficulty and I am not expecting anything. Out of curiosity I unpacked apk today mysefl and yeah, what you did is hell of work.  Agiain thank you for that! And ofcourse I will create new issue. Best!

**Comment by Fito7** [comment]
Today the server came back with all the information, after being busy for a while.
