### ISSUE TITLE
Can't Bind My email

### ISSUE THREAD

**Issue by DG68BB** [ERap320/LenovoWatchMOD#16]
Hey, I'd like some help regarding the App. I've made an account on lenovo.com and when I try to sign in on the app it tells me I need to "bind my email", so I put my email in it asks for a verification that was supposed to be sent out to me. The problem is I don't receive any email! I've tried numerous times and it doesn't work and so IDK what to do :(

**Comment by ERap320** [comment]
Sorry, this looks like a problem of the original app or Lenovo servers. This means it doesn't have anything to do with the mod's code.
Maybe the verification email is in your spam folder. If it's not, try asking on Lenovo's support forums.

**Comment by DG68BB** [comment]
I know it's not your fault I just thought you might be able to help? Were
you able to register? If so did you use Gmail or what email site?
