### ISSUE TITLE
Syncing heart rate, blood pressure, sleep data and mood with lenovo server does not work due to "server busy"

### ISSUE THREAD

**Issue by azagor** [ERap320/LenovoWatchMOD#17]
The issue occurs on all of the latets lenovo watch app versions, staring from 3.1.0 up to 3.1.5. 

Repro:
1. Login to your lenovo account on the app
2. Observe that data is no longer shown on any of the widgets
3. Go to heart rate or blood pressure sub menu and wait for the "server busy" error message to appear

Expected results:
1. Syncing data with the server works
OR
2. Data base is switched to local on your phone ( lenovo server is no longer requied to use all functions of the watch )

Here is it what I was able to find:
1. sources\com\pmpd\protocol\http\sdk\HttpSdkProtocolComponent.java ---> this is a path to a file where comunication with server is handled.
![image](https://user-images.githubusercontent.com/10886050/78588923-aed9bf00-783f-11ea-955d-b3237b12fed6.png)
2. sources/com/pmpd/business/heartrate/model/HeartRateBusinessDayModel.java ---> in here the data is set and get.
![image](https://user-images.githubusercontent.com/10886050/78589198-1ee84500-7840-11ea-9471-62da5842cb87.png)
3. This may aslo be useful sources/com/pmpd/business/heartrate/HeartRateBusinessComponent.java
![image](https://user-images.githubusercontent.com/10886050/78589279-40e1c780-7840-11ea-8fb8-d92ec55481b9.png)

The problem might be connected with a simple bug -  missing letter "c" in here ( maybe they have fixed that on the server side but not in the app code )
![image](https://user-images.githubusercontent.com/10886050/78589717-ed23ae00-7840-11ea-8994-1bee24e98fbb.png)

**Comment by ERap320** [comment]
Looks like this issue was solved with the changes made for #17, so I'll close it for now.
I'll immediately merge these fixes to master.
