### ISSUE TITLE
Watch 9 can't connect

### ISSUE THREAD

**Issue by holloarpad** [ERap320/LenovoWatchMOD#19]
I'm not able to connect my watch 9. The app finds it, but when I try to connect, a short vibration happens on my watch, but won't connect. I'm using miui 10.3 (Android 6) on xiaomi redmi pro.

**Comment by ERap320** [comment]
Does this happen with both the original application and the mod?

**Comment by holloarpad** [comment]
Yes.

**Comment by agrigorev** [comment]
Hello @holloarpad , perhaps, the battery of the watch is empty. According to my previous experience, the battery should be replaced every 4-6 months.
Just an idea...

**Comment by holloarpad** [comment]
Same happens after replacing with a new one. Tried hard reset, reinstalling the app, non-official apps, almost everything I found with the help of Google, this thread is the last chance for the watch, otherwise goes deep in my drawer...

**Comment by ERap320** [comment]
I'm really sorry but I think the most reasonable explaination, after all the things you tried, is that your watch is faulty

**Comment by holloarpad** [comment]
The most sad part of it that I used this watch since last august, and suddenly stopped working without any sign of issues, that's why I thought it was a software error.
