### ISSUE TITLE
Facebook messenger support 

### ISSUE THREAD

**Issue by Dreyar** [ERap320/LenovoWatchMOD#2]
It's  not an issue, more like a feature request. If possible make it work with Facebook messenger notifications.

**Comment by ERap320** [comment]
I'll add Messenger notifications as soon as possible since I can imagine it can be useful to many people.
Unfortunately I don't know how to add more apps than the original app provides, so I'll swap the Android Clock for it.

**Comment by ERap320** [comment]
Facebook Messenger should be working out of the box by activating "Facebook" in the notification menu, even in the unmodded app.

**Comment by Dreyar** [comment]
Its not working(I'm using the official app currently and not your build). 
So if this is an already implemented feature you can close this issue, thanks!

**Comment by ERap320** [comment]
Can you check the package name of your messenger app? I can make sure it is supported and eventually add it in the next commit.
