### ISSUE TITLE
Tencent Tim substitution

### ISSUE THREAD

**Issue by ERap320** [ERap320/LenovoWatchMOD#3]
With version 2.3.3 of the Lenovo Watch app notifications for "Tencent Tim" (another chinese app) became available.

What substitution would you like to be made?

**Comment by bellbill** [comment]
Facebook Messenger, Telegram X, Bluemail (this One expecially but I realize maybe not many use It)

**Comment by ERap320** [comment]
You're not wrong, the latest version is 2.3.4 but, as i said, Tencent Tim was added in version 2.3.3.
Version 2.3.4 is already available in the releases.

Facebook Messenger was mentioned to me by another user in a previous issue, but never tested it myself.
By looking at Lenovo's code it should be working by activating "Facebook" in the notification options.
To be sure, @bellbill can you please tell me the package name (i.e. `com.facebook.orca`) of the Messenger app you are using? I can patch it in the next commit.

I'll probably use Telegram X if nothing better comes up. 

I'm sorry but Bluemail doesn't seem very widespread to me.
I'll probably add Gmail or the default Android Mail app too since I understand that Microsoft Outlook might not be as popular.

**Comment by bellbill** [comment]
I've got com.facebook.orca and com.facebook.katana .
Tested with your Facebook I don't get Messenger notifications.

**Comment by bellbill** [comment]
I see you left tencent Tim in the 2.3.4... Anyway the app wants to Force the 2.3.5 update i had to deactivate mobile data

**Comment by ERap320** [comment]
I'm really sorry for the delay but I'm on vacation and far from all any device I could use to make the new version.

2.3.5 will be ready by Tuesday with the new substitutions.

In the meantime I suggest you to try Gagetbridge like I'm doing. It only supports notifications but it pairs nicely.

It really sucks that the official app doesn't let you do anything if you don't update.

**Comment by bellbill** [comment]
I'll test it for sure.
I'll have to confess to you that I'm actually testing GadgetBridge too, infact I'm just interested about the notifications side.

**Comment by ERap320** [comment]
No problem ;)
I'm using GadgetBridge too, it's just a cleaner solution overall.
I'll try supporting this mod anyway for those who want steps and sleep info, at least until GadgetBridge will do that.
